CREATE TABLE IF NOT EXISTS IDN_TEMPLATE_MGT(
    TEMPLATE_ID INTEGER NOT NULL AUTO_INCREMENT,
    TENANT_ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(1023),
    DATA TEXT NOT NULL,
    PRIMARY KEY (TEMPLATE_ID),
    UNIQUE KEY(TENANT_ID, NAME)
);